import { spawn } from 'child_process';
import simpleGit from 'simple-git';
import fs from 'fs/promises';
import path from 'path';
import { logJobMessage } from '../queue/helpers';
import { config } from '../../config';
import { CompiledErrorReport } from '../errorCollector';

export interface ErrorPrMetadata {
  branchName: string;
  title: string;
  description: string;
  commitMessage: string;
}

export interface ErrorPrResult {
  prUrl: string;
  branchName: string;
  title: string;
  description: string;
}

/**
 * Generate error PR metadata from the compiled error report.
 */
export function generateErrorPrMetadata(report: CompiledErrorReport, jobId: string): ErrorPrMetadata {
  const branchName = `codver-error-${jobId}`;
  const title = `Failed: ${report.errorMessage.substring(0, 80)}`;

  const suggestionsList = report.suggestions.map((s) => `- ${s}`).join('\n');

  const description = `## ❌ Job Failed

**Error Type:** \`${report.errorType}\`  
**Stage:** \`${report.stage}\`  
**Job ID:** \`${jobId}\`

### Error Summary

${report.errorMessage}

### Suggestions

${suggestionsList}

---

### Server Logs

<details>
<summary>Click to expand server logs</summary>

\`\`\`
${report.serverLogs.substring(0, 5000)}
\`\`\`

</details>

### Container Logs

<details>
<summary>Click to expand container logs</summary>

\`\`\`
${report.containerLogs.substring(0, 5000)}
\`\`\`

</details>

### Stack Trace

<details>
<summary>Click to expand stack trace</summary>

\`\`\`
${report.stackTrace.substring(0, 3000)}
\`\`\`

</details>

---

*Generated by Codver* | This is an automated error report.`;

  const commitMessage = `codver: error report for job ${jobId}

${report.errorMessage}

Error Type: ${report.errorType}
Stage: ${report.stage}`;

  return { branchName, title, description, commitMessage };
}

/**
 * Create an error report file in the repo so the PR has a diff.
 */
async function createErrorReportFile(
  projectDir: string,
  report: CompiledErrorReport,
  jobId: string,
): Promise<string> {
  const codverDir = path.join(projectDir, '.codver');
  const reportPath = path.join(codverDir, 'error-report.md');

  try {
    await fs.mkdir(codverDir, { recursive: true });
  } catch {
    // Directory may already exist
  }

  const content = `# Codver Error Report

**Job ID:** ${jobId}  
**Error Type:** ${report.errorType}  
**Stage:** ${report.stage}  
**Time:** ${new Date().toISOString()}

## Summary

${report.errorMessage}

## Suggestions

${report.suggestions.map((s) => `- ${s}`).join('\n')}

---

*This file is generated automatically by Codver for error tracking purposes.*
*It can be safely deleted after reviewing the PR.*
`;

  await fs.writeFile(reportPath, content);
  return reportPath;
}

export async function createErrorGitBranch(
  projectDir: string,
  branchName: string,
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  logJobMessage(jobId, 'info', `Creating error branch: ${branchName}`);
  await git.checkoutLocalBranch(branchName);
  logJobMessage(jobId, 'info', `Error branch created: ${branchName}`);
}

export async function stageErrorReport(
  projectDir: string,
  modifiedFiles: string[],
  errorReportPath: string,
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  const filesToStage = [...modifiedFiles, errorReportPath];
  logJobMessage(jobId, 'info', `Staging ${filesToStage.length} file(s) for error PR`);
  await git.add(filesToStage);
  logJobMessage(jobId, 'info', 'Error report files staged');
}

export async function commitErrorReport(
  projectDir: string,
  message: string,
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  logJobMessage(jobId, 'info', 'Committing error report');
  await git.commit(message, undefined, {
    '--no-verify': null,
  });
  logJobMessage(jobId, 'info', 'Error report committed');
}

export async function pushErrorBranch(
  projectDir: string,
  branchName: string,
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  logJobMessage(jobId, 'info', `Pushing error branch: ${branchName}`);

  const remotes = await git.getRemotes(true);
  const origin = remotes.find((r) => r.name === 'origin');

  if (origin && config.GITHUB_TOKEN) {
    const authUrl = getAuthenticatedUrl(origin.refs.push);
    if (authUrl !== origin.refs.push) {
      try {
        await git.addRemote('codver-error-push', authUrl);
      } catch {
        // Remote might already exist
      }
      await git.push('codver-error-push', branchName, { '--set-upstream': null });
      logJobMessage(jobId, 'info', 'Error branch pushed with token auth');
      return;
    }
  }

  await git.push('origin', branchName, { '--set-upstream': null });
  logJobMessage(jobId, 'info', 'Error branch pushed');
}

export async function createErrorPullRequest(
  projectDir: string,
  metadata: ErrorPrMetadata,
  jobId: string,
): Promise<string> {
  const { branchName, title, description } = metadata;
  logJobMessage(jobId, 'info', `Creating error PR: "${title}"`);

  return new Promise((resolve, reject) => {
    const args = [
      'pr', 'create',
      '--title', title,
      '--body', description,
      '--head', branchName,
      '--repo', '.',
    ];

    const proc = spawn('gh', args, {
      cwd: projectDir,
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    proc.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      if (code === 0) {
        const prUrl = stdout.trim().split('\n').pop() || stdout.trim();
        logJobMessage(jobId, 'info', `Error PR created: ${prUrl}`);
        resolve(prUrl);
      } else {
        const error = new Error(`gh pr create failed for error PR: ${stderr || stdout}`);
        logJobMessage(jobId, 'error', error.message);
        reject(error);
      }
    });

    proc.on('error', (err) => {
      logJobMessage(jobId, 'error', `Failed to run gh pr create for error report: ${err.message}`);
      reject(err);
    });
  });
}

function getAuthenticatedUrl(repoUrl: string): string {
  const token = config.GITHUB_TOKEN;
  if (!token) {
    return repoUrl;
  }

  try {
    const url = new URL(repoUrl);
    if (url.hostname === 'github.com') {
      url.username = token;
      url.password = 'x-oauth-basic';
      return url.toString();
    }
  } catch {
    // If URL parsing fails, return original
  }

  return repoUrl;
}

/**
 * Create a failure/error PR from the compiled error report.
 * If the repo was successfully cloned, this creates a branch with the error report
 * and opens a PR so the user can see what went wrong.
 */
export async function createErrorPr(
  jobId: string,
  projectDir: string,
  report: CompiledErrorReport,
  partialModifiedFiles: string[] = [],
): Promise<ErrorPrResult | null> {
  try {
    // Check if projectDir exists (repo might not have been cloned)
    try {
      await fs.access(projectDir);
    } catch {
      logJobMessage(jobId, 'warn', `Cannot create error PR: project directory does not exist (${projectDir})`);
      return null;
    }

    const metadata = generateErrorPrMetadata(report, jobId);
    logJobMessage(jobId, 'info', `Error branch: ${metadata.branchName}`);
    logJobMessage(jobId, 'info', `Error PR title: "${metadata.title}"`);

    // Create error report file so PR has a diff
    const errorReportPath = await createErrorReportFile(projectDir, report, jobId);

    // Create branch
    await createErrorGitBranch(projectDir, metadata.branchName, jobId);

    // Stage partial changes + error report
    await stageErrorReport(projectDir, partialModifiedFiles, errorReportPath, jobId);

    // Commit
    await commitErrorReport(projectDir, metadata.commitMessage, jobId);

    // Push
    await pushErrorBranch(projectDir, metadata.branchName, jobId);

    // Create PR
    const prUrl = await createErrorPullRequest(projectDir, metadata, jobId);

    return {
      prUrl,
      branchName: metadata.branchName,
      title: metadata.title,
      description: metadata.description,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    logJobMessage(jobId, 'error', `Failed to create error PR: ${message}`);
    return null;
  }
}
