import { spawn } from 'child_process';
import simpleGit from 'simple-git';
import { logJobMessage } from '../queue/helpers';
import { config } from '../../config';

export interface PrMetadata {
  branchName: string;
  title: string;
  description: string;
  commitMessage: string;
}

export interface PrResult {
  prUrl: string;
  branchName: string;
  title: string;
  description: string;
}

/**
 * Generate PR metadata from the original prompt and diff.
 * Uses heuristic-based generation. Can be enhanced with AI calls.
 */
export function generatePrMetadata(prompt: string, modifiedFiles: string[], jobId: string): PrMetadata {
  // Slugify the prompt for branch name
  const slug = prompt
    .toLowerCase()
    .replace(/[^a-z0-9\s]+/g, '')
    .trim()
    .split(/\s+/)
    .slice(0, 6)
    .join('-')
    .substring(0, 50);

  const branchName = `feat/${slug || 'codver-change'}-${jobId}`;

  // Use first sentence or first 80 chars as title
  const title = prompt
    .split(/[.!?]/)
    .filter((s) => s.trim().length > 0)[0]
    ?.trim()
    .substring(0, 80) || `Codver update: ${jobId}`;

  // Generate description
  const fileList = modifiedFiles.length > 0
    ? modifiedFiles.map((f) => `- \`${f}\``).join('\n')
    : '- _No files modified_';

  const description = `## Summary

${prompt}

## Changes

${fileList}

---

*Generated by Codver* | Job ID: \`${jobId}\``;

  const commitMessage = `${title}\n\n${prompt}\n\nChanges:\n${fileList.replace(/`/g, '')}`;

  return { branchName, title, description, commitMessage };
}

export async function createGitBranch(
  projectDir: string,
  branchName: string,
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  logJobMessage(jobId, 'info', `Creating branch: ${branchName}`);
  await git.checkoutLocalBranch(branchName);
  logJobMessage(jobId, 'info', `Branch created: ${branchName}`);
}

export async function stageChanges(
  projectDir: string,
  modifiedFiles: string[],
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  if (modifiedFiles.length === 0) {
    logJobMessage(jobId, 'warn', 'No modified files to stage');
    return;
  }
  logJobMessage(jobId, 'info', `Staging ${modifiedFiles.length} file(s)`);
  await git.add(modifiedFiles);
  logJobMessage(jobId, 'info', 'Changes staged');
}

export async function commitChanges(
  projectDir: string,
  message: string,
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  logJobMessage(jobId, 'info', 'Committing changes');
  await git.commit(message, undefined, {
    '--no-verify': null,
  });
  logJobMessage(jobId, 'info', 'Changes committed');
}

export async function pushBranch(
  projectDir: string,
  branchName: string,
  jobId: string,
): Promise<void> {
  const git = simpleGit(projectDir);
  logJobMessage(jobId, 'info', `Pushing branch: ${branchName}`);

  // Configure auth URL if GITHUB_TOKEN is available
  const remotes = await git.getRemotes(true);
  const origin = remotes.find((r) => r.name === 'origin');

  if (origin && config.GITHUB_TOKEN) {
    const authUrl = getAuthenticatedUrl(origin.refs.push);
    if (authUrl !== origin.refs.push) {
      await git.addRemote('codver-push', authUrl);
      await git.push('codver-push', branchName, { '--set-upstream': null });
      logJobMessage(jobId, 'info', 'Branch pushed with token auth');
      return;
    }
  }

  await git.push('origin', branchName, { '--set-upstream': null });
  logJobMessage(jobId, 'info', 'Branch pushed');
}

export async function createPullRequest(
  projectDir: string,
  metadata: PrMetadata,
  jobId: string,
): Promise<string> {
  const { branchName, title, description } = metadata;
  logJobMessage(jobId, 'info', `Creating PR: "${title}"`);

  return new Promise((resolve, reject) => {
    const args = [
      'pr', 'create',
      '--title', title,
      '--body', description,
      '--head', branchName,
      '--repo', '.',
    ];

    const proc = spawn('gh', args, {
      cwd: projectDir,
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    proc.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      if (code === 0) {
        const prUrl = stdout.trim().split('\n').pop() || stdout.trim();
        logJobMessage(jobId, 'info', `PR created: ${prUrl}`);
        resolve(prUrl);
      } else {
        const error = new Error(`gh pr create failed: ${stderr || stdout}`);
        logJobMessage(jobId, 'error', error.message);
        reject(error);
      }
    });

    proc.on('error', (err) => {
      logJobMessage(jobId, 'error', `Failed to run gh pr create: ${err.message}`);
      reject(err);
    });
  });
}

function getAuthenticatedUrl(repoUrl: string): string {
  const token = config.GITHUB_TOKEN;
  if (!token) {
    return repoUrl;
  }

  try {
    const url = new URL(repoUrl);
    if (url.hostname === 'github.com') {
      url.username = token;
      url.password = 'x-oauth-basic';
      return url.toString();
    }
  } catch {
    // If URL parsing fails, return original
  }

  return repoUrl;
}

export async function createPr(
  jobId: string,
  projectDir: string,
  prompt: string,
  modifiedFiles: string[],
): Promise<PrResult> {
  // Generate metadata
  const metadata = generatePrMetadata(prompt, modifiedFiles, jobId);
  logJobMessage(jobId, 'info', `Branch: ${metadata.branchName}`);
  logJobMessage(jobId, 'info', `Title: "${metadata.title}"`);

  // Create branch
  await createGitBranch(projectDir, metadata.branchName, jobId);

  // Stage changes
  await stageChanges(projectDir, modifiedFiles, jobId);

  // Commit
  await commitChanges(projectDir, metadata.commitMessage, jobId);

  // Push
  await pushBranch(projectDir, metadata.branchName, jobId);

  // Create PR
  const prUrl = await createPullRequest(projectDir, metadata, jobId);

  return {
    prUrl,
    branchName: metadata.branchName,
    title: metadata.title,
    description: metadata.description,
  };
}
