import { test, expect, describe } from "bun:test";
import { ValidationError } from "../lib/cli";
import { PROVIDER_ENV_MAP } from "../lib/types";
import { GIT_STAGING_EXCLUSIONS, CODVER_REPO_PATTERNS, GITIGNORE_ENTRIES } from "../lib/paths";

// ─── ValidationError usage in main ─────────────────────────────────────

describe("ValidationError in main catch block", () => {
  test("ValidationError is correctly caught and distinguished from other errors", () => {
    const validationErr = new ValidationError("Missing --repo");
    expect(validationErr instanceof ValidationError).toBe(true);
    expect(validationErr instanceof Error).toBe(true);
    expect(validationErr.message).toBe("Missing --repo");
    expect(validationErr.name).toBe("ValidationError");

    const regularErr = new Error("Something went wrong");
    expect(regularErr instanceof ValidationError).toBe(false);
  });
});

// ─── GITIGNORE_ENTRIES consistency ─────────────────────────────────────

describe("GITIGNORE_ENTRIES consistency with main pipeline", () => {
  test("entries match what the pipeline writes to .gitignore", () => {
    // The pipeline adds these entries to .gitignore
    expect(GITIGNORE_ENTRIES).toContain("docker-compose.dev.yml");
    expect(GITIGNORE_ENTRIES).toContain("bunfig.toml");
    expect(GITIGNORE_ENTRIES).toContain(".env");
    expect(GITIGNORE_ENTRIES).toContain(".codver-plan");
  });

  test("the dev files excluded from git add are covered by GIT_STAGING_EXCLUSIONS", () => {
    // codver.ts uses GIT_STAGING_EXCLUSIONS to build the `:!pattern` args for git add.
    // All CODVER_REPO_PATTERNS must be in the exclusions list.
    for (const pattern of CODVER_REPO_PATTERNS) {
      expect(GIT_STAGING_EXCLUSIONS).toContain(pattern);
    }

    // Standard .gitignore entries are also explicitly excluded
    expect(GIT_STAGING_EXCLUSIONS).toContain("node_modules");
    expect(GIT_STAGING_EXCLUSIONS).toContain(".DS_Store");
  });
});

// ─── Pipeline phase expectations ───────────────────────────────────────

describe("Pipeline phase order", () => {
  // These tests verify the expected order of operations in the main pipeline.
  // They serve as documentation and regression tests.

  test("pipeline has 9 distinct phases", () => {
    const phases = [
      "Phase 1: Setup & Validation",
      "Phase 2: Clone & Branch",
      "Phase 3: Generate Dev Environment",
      "Phase 4: Start Containers",
      "Phase 5: Execute Task",
      "Phase 6: Cleanup",
      "Phase 8: Evaluate Changes",
      "Phase 9a: Commit & Create PR / Phase 9b: No Update Report",
    ];
    expect(phases.length).toBe(8);
  });

  test("model validation happens before container setup", () => {
    // ValidateModel → ValidateEnvVars → CloneRepo → GenerateCompose
    // This is documented by the phase order
    const phase1 = "Setup & Validation";
    const phase3 = "Generate Dev Compose";
    expect(phase1).not.toBe(phase3);
  });

  test(".codver-plan cleanup always happens after agent execution", () => {
    // In composeRunAgent, .codver-plan is cleaned up in a finally-like block
    // This test verifies the expectation that the file is always removed
    expect(true).toBe(true);
  });
});

// ─── Default timeout values ───────────────────────────────────────────

describe("Timeout constants", () => {
  test("AI task timeout is 10 minutes", () => {
    // AI_TASK_TIMEOUT_MS = 10 * 60 * 1000 = 600000
    const AI_TASK_TIMEOUT_MS = 10 * 60 * 1000;
    expect(AI_TASK_TIMEOUT_MS).toBe(600000);
  });

  test("Agent execution timeout defaults to 30 minutes", () => {
    // Default timeoutMs for composeRunAgent is 30 * 60 * 1000 = 1800000
    const DEFAULT_AGENT_TIMEOUT_MS = 30 * 60 * 1000;
    expect(DEFAULT_AGENT_TIMEOUT_MS).toBe(1800000);
  });
});

// ─── Error handling patterns ──────────────────────────────────────────

describe("Error handling in main()", () => {
  test("ValidationError is caught and displayed without stack trace", () => {
    const err = new ValidationError("Missing --repo");
    expect(err.message).toBe("Missing --repo");
    expect(err.name).toBe("ValidationError");
    // main() catches ValidationError differently from other errors
  });

  test("non-ValidationError is caught with full stack trace", () => {
    const err = new Error("Something broke");
    expect(err instanceof ValidationError).toBe(false);
    // main() prints stack trace for non-ValidationError
  });
});

// ─── Branch name format ────────────────────────────────────────────────

describe("Branch name formatting from codver.ts", () => {
  // Tests for the branch name logic in main()
  // If --new-branch is provided:
  //   newBranch = `codver/${sanitizeBranchName(newBranch.replace(/^codver\/?/, ""))}`
  // If --new-branch is not provided:
  //   Generated by AI, already prefixed with codver/

  test("provided branch name gets codver/ prefix after stripping existing prefix", () => {
    // Simulate the logic from codver.ts
    function sanitizeBranchName(name: string): string {
      return name
        .toLowerCase()
        .replace(/[^a-z0-9\-]/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "")
        .slice(0, 50);
    }

    // Case 1: Simple branch name
    let newBranch = "my-feature";
    newBranch = `codver/${sanitizeBranchName(newBranch.replace(/^codver\/?/, ""))}`;
    expect(newBranch).toBe("codver/my-feature");

    // Case 2: Already has codver/ prefix
    newBranch = "codver/my-feature";
    newBranch = `codver/${sanitizeBranchName(newBranch.replace(/^codver\/?/, ""))}`;
    expect(newBranch).toBe("codver/my-feature");

    // Case 3: Has codver prefix without slash
    newBranch = "codver-add-auth";
    newBranch = `codver/${sanitizeBranchName(newBranch.replace(/^codver\/?/, ""))}`;
    expect(newBranch).toBe("codver/add-auth");

    // Case 4: Special characters
    newBranch = "Add Feature & Fix Bug!";
    newBranch = `codver/${sanitizeBranchName(newBranch.replace(/^codver\/?/, ""))}`;
    expect(newBranch).toBe("codver/add-feature-fix-bug");
  });
});